DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU (
    ID_MENU BIGINT NOT NULL,
    NOMBRE VARCHAR(500) NOT NULL,
    CONSTRAINT PK_MENU PRIMARY KEY (ID_MENU)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8MB4;

DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL (
    ID_ROL BIGINT NOT NULL,
    NOMBRE VARCHAR(500) NOT NULL,
    ACTIVO INTEGER NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8MB4;

DROP TABLE IF EXISTS ROL_MENU;
CREATE TABLE ROL_MENU (
    id_rol BIGINT NOT NULL,
    id_menu BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    CONSTRAINT PK_ROL_MENU PRIMARY KEY (ID_ROL, ID_MENU),
    CONSTRAINT FK_ROL_MENU_1 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL),
    CONSTRAINT FK_ROL_MENU_2 FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8MB4;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
    ID_USUARIO BIGINT NOT NULL,
    NOMBRE_COMPLETO VARCHAR(500) NOT NULL,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(200),
    ACTIVO INTEGER NOT NULL,
    DESCRIPCION TEXT,
    ID_ROL BIGINT NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_1 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8MB4;

DROP TABLE IF EXISTS PROVEEDOR_GPS;
CREATE TABLE PROVEEDOR_GPS (
    ID_PROVEEDOR BIGINT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    URL_SERVICIO VARCHAR(500) NOT NULL,
    ACTIVO INTEGER NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8MB4;

DROP TABLE IF EXISTS VIAJES;
CREATE TABLE VIAJES (
    CODIGO_PAIS VARCHAR(3) NOT NULL,
    NOMBRE_PAIS VARCHAR(200) NOT NULL,
    CODIGO_COMPANIA VARCHAR(10) NOT NULL,
    NOMBRE_COMPANIA VARCHAR(200) NOT NULL,
    CODIGO_PLANTA BIGINT NOT NULL,
    NOMBRE_PLANTA VARCHAR(200) NOT NULL,
    NUMERO_VIAJE BIGINT NOT NULL,
    FECHA_VIAJE DATE NOT NULL,
    CODIGO_ESTADO_VIAJE INTEGER NOT NULL,
    NOMBRE_ESTADO_VIAJE VARCHAR(200) NOT NULL,
    VEHICULO VARCHAR(200) NOT NULL,
    PLACA_VEHICULO VARCHAR(50) NOT NULL,
    CODIGO_TRANSPORTISTA BIGINT NOT NULL,
    NOMBRE_TRANSPORTISTA VARCHAR(500) NOT NULL,
    TIPO_ORDEN_VENTA VARCHAR(3) NOT NULL,
    NUMERO_ORDEN_VENTA BIGINT NOT NULL,
    CODIGO_CLIENTE BIGINT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(500) NOT NULL,
    CODIGO_CLIENTE_DESTINO BIGINT NOT NULL,
    NOMBRE_CLIENTE_DESTINO VARCHAR(500) NOT NULL,
    TIPO_FLETE_VIAJE VARCHAR(3) NOT NULL,
    CONSTRAINT pk_proveedor PRIMARY KEY (CODIGO_PAIS, CODIGO_COMPANIA, CODIGO_PLANTA, NUMERO_VIAJE, TIPO_ORDEN_VENTA, NUMERO_ORDEN_VENTA)
) ENGINE=INNODB DEFAULT CHARACTER SET=UTF8MB4;


INSERT INTO MENU (ID_MENU, NOMBRE) VALUES (1, 'Viajes');
INSERT INTO ROL (ID_ROL, NOMBRE, ACTIVO, FECHA_HORA) VALUES (1, 'Administrador', 1, CURRENT_TIMESTAMP);
INSERT INTO ROL_MENU (ID_ROL, ID_MENU, FECHA_HORA) VALUES (1, 1, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (ID_USUARIO, NOMBRE_COMPLETO, NOMBRE_USUARIO, CONTRASENA, CORREO_ELECTRONICO, ACTIVO, DESCRIPCION, ID_ROL, FECHA_HORA) 
VALUES (1, 'Administrador', 'admin', SHA2('admin2023', 512), 'rmolina@uno-ca.com', 1, 'Usuario admnistrador del sitema.', 1, CURRENT_TIMESTAMP);
INSERT INTO PROVEEDOR_GPS (ID_PROVEEDOR, NOMBRE, URL_SERVICIO, ACTIVO, FECHA_HORA) VALUES (1, 'SMS-OPEN', 'http://190.120.7.3/wsunopetrol/service.asmx?WSDL', 1, CURRENT_TIMESTAMP);


SELECT A.* FROM MENU A;
SELECT A.* FROM ROL A;
SELECT A.* FROM ROL_MENU A;
SELECT A.* FROM USUARIO A;
SELECT A.* FROM PROVEEDOR_GPS A;

SELECT A.* FROM VIAJES A;
SELECT COUNT(*) NUMERO FROM VIAJES A;
